# Generated by Django 4.2.6 on 2023-10-07 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("adminapp", "0023_remove_course_credits_remove_course_ltps_struct_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseContent",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("description", models.TextField(max_length=1000)),
                ("link", models.CharField(max_length=100)),
                ("contentimage", models.FileField(upload_to="coursecontent")),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="adminapp.course",
                    ),
                ),
                (
                    "faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="adminapp.faculty",
                    ),
                ),
            ],
            options={
                "db_table": "coursecontent_table",
            },
        ),
    ]
