# Generated by Django 4.2.5 on 2023-10-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adminapp", "0016_remove_course_credits_remove_course_ltps_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fcoursemappings",
            name="component",
            field=models.CharField(
                choices=[
                    ("L", "Lecture"),
                    ("T", "Tutorial"),
                    ("P", "Practical"),
                    ("S", "Skilling"),
                ],
                default=0,
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fcoursemappings",
            name="section",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fcoursemappings",
            name="type",
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
