# Generated by Django 4.2.5 on 2023-10-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adminapp", "0019_alter_course_coursecredits"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="coursecredits",
            field=models.FloatField(null=True),
        ),
    ]
