# Generated by Django 4.2.5 on 2023-10-06 14:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("adminapp", "0020_alter_course_coursecredits"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="coursecredits",
        ),
        migrations.RemoveField(
            model_name="course",
            name="ltps_struct",
        ),
    ]
