# Generated by Django 4.2.5 on 2023-10-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adminapp", "0021_remove_course_coursecredits_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="Credits",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="LTPS_struct",
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
