# Generated by Django 4.2.5 on 2023-10-06 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adminapp", "0022_course_credits_course_ltps_struct"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="Credits",
        ),
        migrations.RemoveField(
            model_name="course",
            name="LTPS_struct",
        ),
        migrations.AddField(
            model_name="course",
            name="CourseCredits",
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="course",
            name="LTPS_Struct",
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
