# Generated by Django 4.2.6 on 2023-10-10 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("adminapp", "0023_remove_course_credits_remove_course_ltps_struct_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Studentcourses",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "Course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="adminapp.course",
                    ),
                ),
                (
                    "faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="adminapp.faculty",
                    ),
                ),
            ],
            options={
                "db_table": "studentcourse_table",
            },
        ),
    ]
