# Generated by Django 4.2.6 on 2023-11-04 09:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adminapp", "0024_studentcourses"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="program",
            field=models.CharField(
                choices=[("BTECH", "BTECH"), ("MTECH", "MTECH")],
                default=0,
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="course",
            name="department",
            field=models.CharField(
                choices=[
                    ("CSE(R)", "CSE(Regular)"),
                    ("CSE(H)", "CSE(Honors)"),
                    ("CSIT", "CS&IT"),
                    ("ECE", "ECE"),
                    ("EEE", "EEE"),
                    ("ME", "Mech"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="faculty",
            name="department",
            field=models.CharField(
                choices=[
                    ("CSE(R)", "CSE(Regular)"),
                    ("CSE(H)", "CSE(Honors)"),
                    ("CSIT", "CS&IT"),
                    ("ECE", "ECE"),
                    ("EEE", "EEE"),
                    ("ME", "Mech"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="department",
            field=models.CharField(
                choices=[
                    ("CSE(R)", "CSE(Regular)"),
                    ("CSE(H)", "CSE(Honors)"),
                    ("CSIT", "CS&IT"),
                    ("ECE", "ECE"),
                    ("EEE", "EEE"),
                    ("ME", "Mech"),
                ],
                max_length=50,
            ),
        ),
    ]
