# Generated by Django 4.2.6 on 2023-11-04 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adminapp", "0025_course_program_alter_course_department_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="department",
            field=models.CharField(
                choices=[
                    ("CSE(R)", "CSE(Regular)"),
                    ("CSE(H)", "CSE(Honors)"),
                    ("CSIT", "CS&IT"),
                    ("ECE", "ECE"),
                    ("EEE", "EEE"),
                    ("ME", "Mech"),
                    ("BBA", "BBA"),
                    ("BCA", "BCA"),
                    ("MCA", "MCA"),
                    ("MBA", "MBA"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="program",
            field=models.CharField(
                choices=[("BTECH", "BTECH"), ("MTECH", "MTECH"), ("DEGREE", "DEGREE")],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="department",
            field=models.CharField(
                choices=[
                    ("CSE(R)", "CSE(Regular)"),
                    ("CSE(H)", "CSE(Honors)"),
                    ("CSIT", "CS&IT"),
                    ("ECE", "ECE"),
                    ("EEE", "EEE"),
                    ("ME", "Mech"),
                    ("BBA", "BBA"),
                    ("BCA", "BCA"),
                    ("MCA", "MCA"),
                    ("MBA", "MBA"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="program",
            field=models.CharField(
                choices=[("BTECH", "BTECH"), ("MTECH", "MTECH"), ("DEGREE", "DEGREE")],
                max_length=50,
            ),
        ),
    ]
